databases:
  - name: bookmyseat-db
    plan: free
    region: singapore

services:
  - type: redis
    name: bookmyseat-redis
    plan: free
    region: singapore
    ipAllowList: []

  - type: web
    name: bookmyseat
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn bookmyseat.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookmyseat-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: bookmyseat-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com

  - type: worker
    name: bookmyseat-celery-worker
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A bookmyseat worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookmyseat-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: bookmyseat-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"